spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logical-thinking
    username: postgres
    password: postgres
  jmx:
    default-domain: lt

#server:
#  servlet:
#    context-path: /lt
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    jp:
      co:
        runy:
          logical_thinking:
            mapper: DEBUG

# ヘッダーの最大値をデフォルト8KB→64KB(400エラー回避のため)
server:
  max-http-header-size: 64000

#  mapper-locations: classpath*:/jp/co/runy/logical_thinking/mapper/*.xml